### ISSUE TITLE
Some documentation tweaks

### ISSUE THREAD

**Issue by zephyrr** [nRF24/RF24Audio#1]
Quick notes on Doxygen docs:
In the Constructor, the note might say "radioNum is only needed..."
broadcast seems kind of oddly named (turns OFF broadcasting except for 255)
Example for setVolume uses .volume()

Overall, really cool project!

**Comment by 2bndy5** [comment]
@TMRh20 do you have a copy of the doxyfile for this repo? it doesn't seem to be in the repo (unless I'm missing it somewhere)

**Comment by TMRh20** [comment]
Added
