### ISSUE TITLE
Is IRQ pin used?  Not getting sound

### ISSUE THREAD

**Issue by becauseinterwebs** [nRF24/RF24Audio#14]
I don't want to post a generic "it's not working" question since I just got it all hooked up ;)  I noticed in the wiring diagrams the IRQ pin is not connected to anything.  Is this correct?  I'm just getting a high pitched whine on my speaker and on my other board (Nano) the TX and RX lights are constantly lit.

**Comment by TMRh20** [comment]
Nope, irq pin not used. It should be quiet until something is sent.
