### ISSUE TITLE
RF24Audio is working with DUE?

### ISSUE THREAD

**Issue by alkuentrus** [nRF24/RF24Audio#17]
Hello. 
I have been testing your examples, from RF24MasterAudio with several boards. However, I haven't still managed to compile any of them using arduino Due. 
Thank you for you attention.
[errors_Ardu_Due.txt](https://github.com/nRF24/RF24Audio/files/1865037/errors_Ardu_Due.txt)

**Comment by TMRh20** [comment]
It’s only for AVR devices. AAAudio is another audio library for the Due that is somewhat compatible with rf24audio. The radio addresses just need to be configured the same. https://github.com/TMRh20/AutoAnalogAudio
