### ISSUE TITLE
multi receiver headphone

### ISSUE THREAD

**Issue by maramb81** [nRF24/RF24Audio#20]
Hi Guys 
could i ask, how many receiver could i use with one tx ? 
i want to create a wireless headphone system with about 80 receiver headphone

is it possible ?

thank you

**Comment by maramb81** [comment]
we want to create a silent disco party system with cheap headphone, image a disco party without music but just headphone. Standard system use UHF transmission and has three switch to select a kind of music, we want just one tx so you could listen just one dj.

**Comment by umerkhanfarooq** [comment]
i am making a system in which i have two transmitters and two receivers but when i start both transmitter and receiver my receivers leds start blinking.transmitters are disturbing my  receivers.......

**Comment by umerkhanfarooq** [comment]
![problem](https://user-images.githubusercontent.com/9510853/43370529-dc3151e8-9399-11e8-82b3-c06e9edfc5dc.png)
![problem](https://user-images.githubusercontent.com/9510853/43370533-ea3b96cc-9399-11e8-819b-702186a2d09b.png)

**Comment by umerkhanfarooq** [comment]
or may be my receivers are listening both transmitter.
