### ISSUE TITLE
RF24Audio with TRRS Audio Jack for use with Headphones?

### ISSUE THREAD

**Issue by GlitchyCzE** [nRF24/RF24Audio#22]
Hello, I was wondering how this diagram:
![image](https://user-images.githubusercontent.com/13904731/46643992-7246dd80-cb4c-11e8-9cbd-b4215c69192f.png)
can be modified to instead have the TRRS 3.5mm Jack be utilized for audio output and input.

The jack has four pins: Sleeve, Ring2, Ring1 and Tip. 
![image](https://user-images.githubusercontent.com/13904731/46644067-cf429380-cb4c-11e8-9151-79ced8d72977.png)
What would I change in the sample diagram to get it so that Audio is outputted to the connected headphones and the mic from those headphones are used as an input when transmitting?

**Comment by CzEMC** [comment]
Mic is the Sleeve.
Ring2 is Common Ground.
Ring1 is Right.
Tip is Left.

I assume that the audio coming out of pin 9/10 is mono, so I would be using Right.

However, why does audio IO at pin 9 and 10, why not have the speaker connect to one pin, like pin 9 and the other pin return to ground? 

(Pin 9 -> Speaker -> Arduino Ground) 

I'm confused, as I know that connecting Ring1 and Tip to pins 9 and 10 will not produce the desired outcome as there's no ground/return.

So do I the connect ground (Ring2) to one of those pins, say pin 10 and connect Ring1 (Right) to pin 9?


And for the microphone, I would connect the sleeve to pin A0, and I'm guessing that it will detect sounds by using the electrical resistance to ground?

Thanks in advance for any help and clarification.

**Comment by payamsbr** [comment]
![image](https://user-images.githubusercontent.com/23378659/60971536-a51b3d80-a339-11e9-8d1f-dc1f51a21705.png)

it is what i did for audio jack
