### ISSUE TITLE
fix it (ADCSRB | ADTS bits)

### ISSUE THREAD

**Issue by payamsbr** [nRF24/RF24Audio#23]
**in line 580**, you commented that adc auto trigger is set on **TIMER1 Capture interrupt flag**.
it require ADTS[2:0] to set 1 but in the code you just set ADTS0 twice.
please tell if the code is ok and comment need to be updated. tnx

`ADCSRB |= _BV(ADTS0) | _BV(ADTS0) | _BV(ADTS2);           //Attach ADC start to TIMER1 Capture interrupt flag`

**Comment by TMRh20** [comment]
I think it should work like it is, but the code should be corrected.

**Comment by payamsbr** [comment]
> I think it should work like it is, but the code should be corrected.
> […](#)
> On Jul 10, 2019, at 06:58, payamsbr ***@***.***> wrote: in line 580, you commented that adc auto trigger is set on TIMER1 Capture interrupt flag. it require ADTS[2:0] to set 1 but in the code you just set ADTS0 twice. please tell if the code is ok and comment need to be updated. tnx ADCSRB |= _BV(ADTS0) | _BV(ADTS0) | _BV(ADTS2); //Attach ADC start to TIMER1 Capture interrupt flag — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

i got it, thank you for the response. its a while . its risky to touch any thing when they'r working fine
