### ISSUE TITLE
Disabling complimentary Mode

### ISSUE THREAD

**Issue by alkuentrus** [nRF24/RF24Audio#25]
Hello, Is it possible to turn off the complimentary mode, instead of using 9 and 10, is it possibel to use 9 and Ground? Thank you!

**Comment by TMRh20** [comment]
Kind of. You can’t really disable it, but you can leave pin 10 disabled by not setting pin mode to output. By default it works by connecting the speaker to pin 9 and ground.

**Comment by alkuentrus** [comment]
Thank You
