### ISSUE TITLE
How use library whith arduino rf-nano??

### ISSUE THREAD

**Issue by planer-pro** [nRF24/RF24Audio#31]
Arduino RF-Nano use 9 CSN, 10 CE pins by default circuit. And how to use that library for these situation? Is change output pwm pin on 5,6 it is'n work!

**Comment by TMRh20** [comment]
Unfortunately the decision to use pins 9&10 limits access to the timer1 pins so rf24audio won’t work with the rf-nano at all.

**Comment by planer-pro** [comment]
rf-nano cs&csn pins is a genius solution of stupid engirering!) Пoing to cut tracks and solder jumpers, in order to change to 7 & 8
