### ISSUE TITLE
CT Sensor to Arduino Uno

### ISSUE THREAD

**Issue by calla1** [nRF24/RF24Audio#38]
I am currently trying to interface my CT Sensor with my Arduino Uno, and it comes with an Audio Jack connector, so I purchased a little TRRS breakout module with Pins named: Sleeve, Ring2, Ring 1, and Tip.
I am wondering what pins on the Arduino I would connect these to, so I can read current from my CT Sensor.  

![IMG_20210818_203443](https://user-images.githubusercontent.com/89135029/129883927-94a9b95e-f762-490a-82a4-4b600b3896a4.jpg)
![IMG_20210818_203457](https://user-images.githubusercontent.com/89135029/129883943-6f4c5322-31a5-419e-ba31-3d3e78c43145.jpg)
![IMG_20210818_203431](https://user-images.githubusercontent.com/89135029/129883965-6ea3d5f7-5fbc-4ebd-84b1-57a56fa6446f.jpg)

**Comment by TMRh20** [comment]
I think you connect sleeve to GND and the audio input/output to one or two of the others.

**Comment by calla1** [comment]
So, the audio input/output (possibly the TIP and either ring1 or ring 2), would they connect to two different Analog pins?

**Comment by TMRh20** [comment]
Yup
