### ISSUE TITLE
NRF24L01 Analog Output for Speaker

### ISSUE THREAD

**Issue by AmeerHafez** [nRF24/RF24Audio#39]
Hello there. I tried to read the output of a receiver and the signal looked digitized. Is there anyway to output it in analog form?

And yes I tested it with a normal speaker and it sounds fine but the signal I receive on the oscilloscope looked like a pwm signal

**Comment by Avamander** [comment]
What are you trying to do? What do you mean by "tried to read"?

**Comment by AmeerHafez** [comment]
read as in viewing it on oscilloscope. I'm trying to output analog signal from the receiver side but it looked digitized..

**Comment by TMRh20** [comment]
It is PWM. The smaller Arduino devices don’t have a DAC. The best you can do i think is filter the output to get more of an analog signal.

**Comment by AmeerHafez** [comment]
mhmm .. if i lower the sample rate of the transmission is it going to make it more like an analog signal? I'm planning to have a similar input signal by avoiding filters or DAC .. so what i understand is that arduino nano/uno can not output analog?

**Comment by Avamander** [comment]
> so what i understand is that arduino nano/uno can not output analog?

No, they can't.

**Comment by AmeerHafez** [comment]
> It is PWM. The smaller Arduino devices don’t have a DAC. The best you can do i think is filter the output to get more of an analog signal.
> […](#)

Well what kind of filter? and how do I design the filter? Sorry I'm new to this

**Comment by Avamander** [comment]
A DAC would work better, but you can use a low-pass filter that lets your intended frequency range trough, but filters the rest. There are calculators out there for low-pass filters.

**Comment by AmeerHafez** [comment]
> A DAC would work better, but you can use a low-pass filter that lets your intended frequency range trough, but filters the rest. There are calculators out there for low-pass filters.

mhmm.. is it possible to output the analog signal using arudino duo? It has embedded DAC inside it...

**Comment by TMRh20** [comment]
The auto analogue audio library supports Arduino due but is a bit harder to use.

**Comment by AmeerHafez** [comment]
Ok thank you.. That is what i needed to know
