### ISSUE TITLE
Regarding Fpwm Frequency for Arduino Nano using NRF24L01+

### ISSUE THREAD

**Issue by AmeerHafez** [nRF24/RF24Audio#43]
Hello there, 

I have used the audio library on arduino nano for quite some time and it works very well. I'm doing this for my project and I'm wondering what is the default PWM frequency for audio sampling on the default output D9?. As well, how to change the PWM frequency or access it from the RF24Audio library?..

**Comment by TMRh20** [comment]
The default frequency is 24khz and can be changed by editing the userConfig.h file found in the library folder.

**Comment by AmeerHafez** [comment]
So the PWM frequency is the same as the audio sampling rate?

**Comment by TMRh20** [comment]
Yup!

**Comment by AmeerHafez** [comment]
Thank you :) !
