### ISSUE TITLE
Specific Volume Adjustment

### ISSUE THREAD

**Issue by AmeerHafez** [nRF24/RF24Audio#45]
Is there anyway to set the receiver volume at a specific gain? for example setVolume(1.5)?

**Comment by TMRh20** [comment]
https://nrf24.github.io/RF24Audio/classRF24Audio.html#af379c3a3d32de245746ecb6c27ec8e2c

Yeah its setVolume(0-7);

**Comment by AmeerHafez** [comment]
Oh ok, I thought I can only increase volume with 1 or decrease it with 0. I have an issue where If I set the volume to 1 or above the audio becomes inaudible like just nothing. what could be causing this? Is it the PWM output?
