### ISSUE TITLE
Use without buttons

### ISSUE THREAD

**Issue by CommandMaker** [nRF24/RF24Audio#50]
Hello,
I'd like to build an in-ear monitor system (I'm a musician) and I'd like to use this library to transmit audio over 2 NRF24L01 Arduino Nano. I'd only want a TX mode (I know I can achieve this) but I would also like a continuous stream (not pressing any button). Is there a way to achieve this (I also don't need the volume buttons)

Thank you

**Comment by TMRh20** [comment]
Yes, see the included examples.

On one node, just call `rfAudio.transmit();` in the setup function of the sketch.
In the other, call `rfAudio.receive();`

**Comment by CommandMaker** [comment]
Thanks a lot !
